const Category = require('../models/Category');
const Product = require('../models/Product');
const SubCategory = require('../models/SubCategory');
const Order = require('../models/Order');
const mongoose = require('mongoose');
const { uploadToCloudinary, deleteFromCloudinary } = require('../utils/cloudinary');
const logger = require('../utils/logger');
const { validationResult } = require('express-validator');
const { calculateDistance, parseClientLatLon, toNumberCoord } = require('../utils/distanceUtils');
// Helper function to format response - keep _id for operations but ensure code is present
const formatResponse = (obj) => {
  if (!obj || typeof obj !== 'object') return obj;

  if (Array.isArray(obj)) {
    return obj.map(item => formatResponse(item));
  }

  const cleaned = { ...obj };

  // Ensure _id is converted to string if it's an ObjectId object
  if (cleaned._id) {
    if (typeof cleaned._id === 'object' && cleaned._id !== null) {
      // If it's a MongoDB ObjectId object, convert to string
      if (cleaned._id.toString && typeof cleaned._id.toString === 'function') {
        try {
          const idString = cleaned._id.toString();
          // Only use toString if it doesn't return "[object Object]"
          if (idString !== '[object Object]') {
            cleaned._id = idString;
          } else if (cleaned._id.toHexString && typeof cleaned._id.toHexString === 'function') {
            cleaned._id = cleaned._id.toHexString();
          } else {
            // Fallback: try to get the string value
            cleaned._id = String(cleaned._id);
          }
        } catch (e) {
          cleaned._id = String(cleaned._id);
        }
      } else {
        cleaned._id = String(cleaned._id);
      }
    } else if (typeof cleaned._id !== 'string') {
      cleaned._id = String(cleaned._id);
    }
  }

  // Ensure code is present, keep _id for update operations
  if (cleaned._id && !cleaned.code) {
    // If code doesn't exist, we'll keep _id but code should be generated by model
    // This is just for formatting, code generation happens in model pre-save
  }

  // Recursively format nested objects (but keep _id in nested objects too for references)
  for (const key in cleaned) {
    if (cleaned[key] && typeof cleaned[key] === 'object' && !(cleaned[key] instanceof Date)) {
      cleaned[key] = formatResponse(cleaned[key]);
    }
  }

  return cleaned;
};

exports.createCategory = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array(),
      });
    }

    const { name, description } = req.body;

    const existingCategory = await Category.findOne({ name });
    if (existingCategory) {
      return res.status(400).json({
        success: false,
        error: 'Category with this name already exists',
      });
    }

    let imageData = {};

    if (req.file) {
      try {
        const uploadResult = await uploadToCloudinary(req.file, 'rush-basket/categories');
        imageData = uploadResult;
      } catch (uploadError) {
        logger.error('Cloudinary upload error:', uploadError);
        return res.status(500).json({
          success: false,
          error: 'Failed to upload image',
        });
      }
    }

    const category = await Category.create({
      name,
      description,
      image: imageData.url ? imageData : undefined,
      createdBy: req.admin._id,
    });

    const populatedCategory = await Category.findById(category._id).populate('createdBy', 'name email').lean();

    logger.info(`Category created: ${category.name} by Admin: ${req.admin.email}`);

    // Keep _id for update operations, but code will be used for display
    const responseData = formatResponse({
      ...populatedCategory,
      code: populatedCategory.code,
    });

    res.status(201).json({
      success: true,
      message: 'Category created successfully',
      data: responseData,
    });
  } catch (error) {
    logger.error('Create category error:', error);
    next(error);
  }
};

exports.getCategories = async (req, res, next) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;
    const isActive = req.query.isActive;

    let query = {};
    if (isActive !== undefined) {
      query.isActive = isActive === 'true';
    }

    const categories = await Category.find(query)
      .populate('createdBy', 'name email')
      .skip(skip)
      .limit(limit)
      .sort({ createdAt: -1 })
      .lean();

    // Get total product count for each category
    const categoriesWithProductCount = await Promise.all(
      categories.map(async (category) => {
        const totalProducts = await Product.countDocuments({ category: category._id });
        // Ensure _id is converted to string for frontend compatibility
        const categoryData = {
          ...category,
          _id: category._id ? String(category._id) : category._id,
          code: category.code,
          totalProducts,
          // Ensure image is null if not present (instead of undefined)
          image: category.image && category.image.url ? category.image : null,
        };
        // Keep _id for update operations, code for display
        return formatResponse(categoryData);
      })
    );

    const total = await Category.countDocuments(query);

    res.status(200).json({
      success: true,
      count: categoriesWithProductCount.length,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
      data: categoriesWithProductCount,
    });
  } catch (error) {
    logger.error('Get categories error:', error);
    next(error);
  }
};

/**
 * Get categories that have nearby products
 * Only returns active categories with at least one approved, active, and nearby product
 */
exports.getNearbyCategories = async (req, res, next) => {
  try {
    const { radius = 10, page = 1, limit = 20 } = req.query;

    const parsed = parseClientLatLon(req.query);
    const hasLocation = !!parsed;
    const effectiveHasLocation = hasLocation;
    let userLat;
    let userLon;
    let searchRadius;

    if (hasLocation) {
      userLat = parsed.latitude;
      userLon = parsed.longitude;
      searchRadius = parseFloat(radius) || 10;
      if (parsed.corrected) {
        logger.info('getNearbyCategories: corrected client lat/lon order (South Asia heuristic)');
      }
    }

    const pageNum = parseInt(page) || 1;
    const limitNum = parseInt(limit) || 20;
    const skip = (pageNum - 1) * limitNum;

    const nearbyProductCategoryIds = new Set();

    const productQuery = {
      approvalStatus: 'approved',
      isActive: true,
    };

    if (effectiveHasLocation) {
      productQuery.latitude = { $exists: true, $ne: null };
      productQuery.longitude = { $exists: true, $ne: null };
    }

    const products = await Product.find(productQuery)
      .populate('vendor', 'storeAddress serviceRadius')
      .lean();

    if (effectiveHasLocation) {
      const productsWithDistance = products.map(product => {
        if (!product.vendor || !product.vendor.storeAddress) return null;

        const vendorLat = toNumberCoord(product.vendor.storeAddress.latitude);
        const vendorLon = toNumberCoord(product.vendor.storeAddress.longitude);
        if (!Number.isFinite(vendorLat) || !Number.isFinite(vendorLon)) return null;

        const vendorStoreDistance = calculateDistance(userLat, userLon, vendorLat, vendorLon);
        if (vendorStoreDistance == null) return null;

        let productDistance = null;
        const pLat = toNumberCoord(product.latitude);
        const pLon = toNumberCoord(product.longitude);
        if (Number.isFinite(pLat) && Number.isFinite(pLon)) {
          productDistance = calculateDistance(userLat, userLon, pLat, pLon);
        }

        const minDistance = productDistance != null ? Math.min(vendorStoreDistance, productDistance) : vendorStoreDistance;

        if (minDistance <= searchRadius) {
          return { ...product, minDistance };
        }
        return null;
      }).filter(p => p !== null);

      if (productsWithDistance.length > 0) {
        productsWithDistance.sort((a, b) => a.minDistance - b.minDistance);
        const nearestVendorId = productsWithDistance[0].vendor._id.toString();

        productsWithDistance.forEach(product => {
          if (product.vendor._id.toString() === nearestVendorId && product.category) {
            nearbyProductCategoryIds.add(String(product.category));
          }
        });
      }
    } else {
      products.forEach(product => {
        if (product.category) {
          nearbyProductCategoryIds.add(String(product.category));
        }
      });
    }

    const categoryIdsArray = Array.from(nearbyProductCategoryIds).map(id => new mongoose.Types.ObjectId(id));

    // Query categories matching those IDs
    const categoryQuery = {
      _id: { $in: categoryIdsArray },
      isActive: true, // Only return active categories
    };

    const categories = await Category.find(categoryQuery)
      .populate('createdBy', 'name email')
      .skip(skip)
      .limit(limitNum)
      .sort({ createdAt: -1 })
      .lean();

    // Get product count for each category (optionally restrict to nearby products count)
    // For now, we'll provide the total active product count like getCategories
    const categoriesWithProductCount = await Promise.all(
      categories.map(async (category) => {
        const countFilter = {
          category: category._id,
          approvalStatus: 'approved',
          isActive: true,
        };
        const totalProducts = await Product.countDocuments(countFilter);

        const categoryData = {
          ...category,
          _id: category._id ? String(category._id) : category._id,
          code: category.code,
          totalProducts,
          image: category.image && category.image.url ? category.image : null,
        };
        return formatResponse(categoryData);
      })
    );

    const total = await Category.countDocuments(categoryQuery);

    if (hasLocation) {
      logger.info(`Nearby categories retrieved: Lat: ${userLat}, Lon: ${userLon}, Found: ${total}`);
    } else {
      logger.info(`Categories (with products) retrieved: Found: ${total}`);
    }

    res.status(200).json({
      success: true,
      count: categoriesWithProductCount.length,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total,
        pages: Math.ceil(total / limitNum),
      },
      data: categoriesWithProductCount,
    });
  } catch (error) {
    logger.error('Get nearby categories error:', error);
    if (error.name === 'CastError') {
      return res.status(400).json({
        success: false,
        error: 'Invalid query parameters',
      });
    }
    next(error);
  }
};

exports.getCategory = async (req, res, next) => {
  try {
    const categoryId = req.params.id;

    // Validate MongoDB ObjectId
    if (!mongoose.Types.ObjectId.isValid(categoryId)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid category ID',
      });
    }

    // Get category with populated createdBy
    const category = await Category.findById(categoryId).populate('createdBy', 'name email').lean();

    if (!category) {
      return res.status(404).json({
        success: false,
        error: 'Category not found',
      });
    }

    // Get summary statistics
    const [totalProducts, subCategoriesCount, subCategories] = await Promise.all([
      Product.countDocuments({
        category: categoryId,
        approvalStatus: 'approved',
        isActive: true
      }),
      SubCategory.countDocuments({
        category: categoryId,
        isActive: true
      }),
      SubCategory.find({
        category: categoryId,
        isActive: true
      })
        .select('name code')
        .sort({ createdAt: 1 })
        .lean()
    ]);

    // Get top selling products by aggregating from orders
    const topSellingProducts = await Order.aggregate([
      {
        $unwind: '$items'
      },
      {
        $match: {
          'items.product': { $exists: true },
          status: { $in: ['delivered', 'confirmed', 'processing', 'ready', 'out_for_delivery'] }
        }
      },
      {
        $lookup: {
          from: 'products',
          localField: 'items.product',
          foreignField: '_id',
          as: 'productDetails'
        }
      },
      {
        $unwind: '$productDetails'
      },
      {
        $match: {
          'productDetails.category': new mongoose.Types.ObjectId(categoryId),
          'productDetails.approvalStatus': 'approved',
          'productDetails.isActive': true
        }
      },
      {
        $group: {
          _id: '$items.product',
          productName: { $first: '$productDetails.productName' },
          totalSales: { $sum: '$items.quantity' },
          stock: { $first: '$productDetails.inventory' }
        }
      },
      {
        $sort: { totalSales: -1 }
      },
      {
        $limit: 10
      },
      {
        $project: {
          _id: 1,
          productName: 1,
          sales: '$totalSales',
          stock: 1
        }
      }
    ]);

    // Format top selling products with rank
    const formattedTopProducts = topSellingProducts.map((product, index) => ({
      rank: index + 1,
      productId: product._id,
      productName: product.productName,
      sales: product.sales,
      stock: product.stock
    }));

    // Format sub categories with numbers - keep _id for operations, code for display
    const formattedSubCategories = subCategories.map((subCat, index) => {
      return {
        _id: subCat._id, // Keep for update operations
        code: subCat.code,
        name: subCat.name,
        number: index + 1
      };
    });

    // Format dates
    const formatDate = (date) => {
      if (!date) return null;
      const d = new Date(date);
      const day = String(d.getDate()).padStart(2, '0');
      const month = String(d.getMonth() + 1).padStart(2, '0');
      const year = d.getFullYear();
      return `${day}/${month}/${year}`;
    };

    // Build response - keep _id for update operations, code for display
    const response = {
      success: true,
      data: {
        category: formatResponse({
          ...category,
          code: category.code,
          // Ensure image is null if not present (instead of undefined)
          image: category.image && category.image.url ? category.image : null,
        }),
        summary: {
          totalProducts,
          subCategoriesCount,
          created: formatDate(category.createdAt),
          lastUpdated: formatDate(category.updatedAt)
        },
        topSellingProducts: formattedTopProducts,
        subCategories: formattedSubCategories
      }
    };

    res.status(200).json(response);
  } catch (error) {
    logger.error('Get category error:', error);
    next(error);
  }
};

exports.updateCategory = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array(),
      });
    }

    let category = await Category.findById(req.params.id);

    if (!category) {
      return res.status(404).json({
        success: false,
        error: 'Category not found',
      });
    }

    const { name, description } = req.body;

    if (name && name !== category.name) {
      const existingCategory = await Category.findOne({ name });
      if (existingCategory) {
        return res.status(400).json({
          success: false,
          error: 'Category with this name already exists',
        });
      }
    }

    if (name) category.name = name;
    if (description !== undefined) category.description = description;

    if (req.file) {
      if (category.image && category.image.publicId) {
        try {
          await deleteFromCloudinary(category.image.publicId);
        } catch (deleteError) {
          logger.error('Error deleting old image:', deleteError);
        }
      }

      try {
        const uploadResult = await uploadToCloudinary(req.file, 'rush-basket/categories');
        category.image = uploadResult;
      } catch (uploadError) {
        logger.error('Cloudinary upload error:', uploadError);
        return res.status(500).json({
          success: false,
          error: 'Failed to upload image',
        });
      }
    }

    await category.save();

    const populatedCategory = await Category.findById(category._id).populate('createdBy', 'name email').lean();

    logger.info(`Category updated: ${category.name} by Admin: ${req.admin.email}`);

    // Keep _id for update operations, code for display
    const responseData = formatResponse({
      ...populatedCategory,
      code: populatedCategory.code,
    });

    res.status(200).json({
      success: true,
      message: 'Category updated successfully',
      data: responseData,
    });
  } catch (error) {
    logger.error('Update category error:', error);
    next(error);
  }
};

exports.deleteCategory = async (req, res, next) => {
  try {
    const category = await Category.findById(req.params.id);

    if (!category) {
      return res.status(404).json({
        success: false,
        error: 'Category not found',
      });
    }

    if (category.image && category.image.publicId) {
      try {
        await deleteFromCloudinary(category.image.publicId);
      } catch (deleteError) {
        logger.error('Error deleting image from Cloudinary:', deleteError);
      }
    }

    await Category.findByIdAndDelete(req.params.id);

    logger.info(`Category deleted: ${category.name} by Admin: ${req.admin.email}`);

    res.status(200).json({
      success: true,
      message: 'Category deleted successfully',
    });
  } catch (error) {
    logger.error('Delete category error:', error);
    next(error);
  }
};

exports.toggleCategoryStatus = async (req, res, next) => {
  try {
    const category = await Category.findById(req.params.id);

    if (!category) {
      return res.status(404).json({
        success: false,
        error: 'Category not found',
      });
    }

    category.isActive = !category.isActive;
    await category.save();

    logger.info(`Category status toggled: ${category.name} to ${category.isActive} by Admin: ${req.admin.email}`);

    // Keep _id for update operations, code for display
    const categoryData = category.toObject ? category.toObject() : category;
    const responseData = formatResponse({
      ...categoryData,
      code: category.code,
    });

    res.status(200).json({
      success: true,
      message: `Category ${category.isActive ? 'activated' : 'deactivated'} successfully`,
      data: responseData,
    });
  } catch (error) {
    logger.error('Toggle category status error:', error);
    next(error);
  }
};

