const SubCategory = require('../models/SubCategory');
const Category = require('../models/Category');
const Product = require('../models/Product');
const Vendor = require('../models/Vendor');
const { uploadToCloudinary, deleteFromCloudinary } = require('../utils/cloudinary');
const logger = require('../utils/logger');
const { validationResult } = require('express-validator');
const { calculateDistance, parseClientLatLon, toNumberCoord } = require('../utils/distanceUtils');
// Helper function to format response - keep _id for operations but ensure code is present
const formatResponse = (obj) => {
  if (!obj || typeof obj !== 'object') return obj;

  if (Array.isArray(obj)) {
    return obj.map(item => formatResponse(item));
  }

  const cleaned = { ...obj };
  const mongoose = require('mongoose');

  // Convert _id to string if it exists (handles Buffer objects and ObjectIds)
  if (cleaned._id) {
    if (cleaned._id.buffer && Array.isArray(cleaned._id.buffer)) {
      // Handle Buffer object with buffer property - convert to ObjectId string
      try {
        const buffer = Buffer.from(cleaned._id.buffer);
        cleaned._id = new mongoose.Types.ObjectId(buffer).toString();
      } catch (e) {
        // Fallback: convert buffer to hex string (24 chars for ObjectId)
        cleaned._id = Buffer.from(cleaned._id.buffer).toString('hex');
      }
    } else if (cleaned._id.toString && typeof cleaned._id.toString === 'function' && cleaned._id.constructor && cleaned._id.constructor.name === 'ObjectId') {
      // Handle Mongoose ObjectId
      cleaned._id = cleaned._id.toString();
    } else if (typeof cleaned._id !== 'string') {
      // Convert any other type to string
      try {
        cleaned._id = String(cleaned._id);
      } catch (e) {
        // If conversion fails, try ObjectId conversion
        try {
          cleaned._id = new mongoose.Types.ObjectId(cleaned._id).toString();
        } catch (e2) {
          cleaned._id = cleaned._id;
        }
      }
    }
  }

  // Ensure code is present, keep _id for update operations
  if (cleaned._id && !cleaned.code) {
    // If code doesn't exist, we'll keep _id but code should be generated by model
    // This is just for formatting, code generation happens in model pre-save
  }

  // Recursively format nested objects (but keep _id in nested objects too for references)
  for (const key in cleaned) {
    if (cleaned[key] && typeof cleaned[key] === 'object' && !(cleaned[key] instanceof Date) && !(cleaned[key] instanceof Buffer)) {
      // Process nested objects, but skip Buffer objects (they're handled above for _id)
      cleaned[key] = formatResponse(cleaned[key]);
    }
  }

  return cleaned;
};


exports.createSubCategory = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array(),
      });
    }

    const { name, description, category } = req.body;

    const parentCategory = await Category.findById(category);
    if (!parentCategory) {
      return res.status(404).json({
        success: false,
        error: 'Parent category not found',
      });
    }

    const existingSubCategory = await SubCategory.findOne({ name, category });
    if (existingSubCategory) {
      return res.status(400).json({
        success: false,
        error: 'SubCategory with this name already exists in this category',
      });
    }

    let imageData = {};

    if (req.file) {
      try {
        const uploadResult = await uploadToCloudinary(req.file, 'rush-basket/subcategories');
        imageData = uploadResult;
      } catch (uploadError) {
        logger.error('Cloudinary upload error:', uploadError);
        return res.status(500).json({
          success: false,
          error: 'Failed to upload image',
        });
      }
    }

    const subCategory = await SubCategory.create({
      name,
      description,
      category,
      image: imageData.url ? imageData : undefined,
      createdBy: req.admin._id,
    });

    // Increment subCategoryCount in the parent category
    await Category.findByIdAndUpdate(category, {
      $inc: { subCategoryCount: 1 },
    });

    const populatedSubCategory = await SubCategory.findById(subCategory._id)
      .populate('category', 'name code')
      .populate('createdBy', 'name email')
      .lean();

    logger.info(`SubCategory created: ${subCategory.name} by Admin: ${req.admin.email}`);

    // Keep _id for update operations, code for display
    const responseData = formatResponse({
      ...populatedSubCategory,
      code: populatedSubCategory.code,
      category: populatedSubCategory.category ? {
        ...populatedSubCategory.category,
        code: populatedSubCategory.category.code,
      } : populatedSubCategory.category,
    });

    res.status(201).json({
      success: true,
      message: 'SubCategory created successfully',
      data: responseData,
    });
  } catch (error) {
    logger.error('Create subcategory error:', error);
    next(error);
  }
};

exports.getSubCategories = async (req, res, next) => {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;
    const isActive = req.query.isActive;
    const category = req.query.category;

    let query = {};
    if (isActive !== undefined) {
      query.isActive = isActive === 'true';
    }
    if (category) {
      query.category = category;
    }

    const subCategories = await SubCategory.find(query)
      .populate('category', 'name code')
      .populate('createdBy', 'name email')
      .skip(skip)
      .limit(limit)
      .sort({ createdAt: -1 })
      .lean();

    const total = await SubCategory.countDocuments(query);

    // Keep _id for update operations, code for display
    const formattedSubCategories = subCategories.map((subCat) => {
      return formatResponse({
        ...subCat,
        code: subCat.code,
        category: subCat.category ? {
          ...subCat.category,
          code: subCat.category.code,
        } : subCat.category,
      });
    });

    res.status(200).json({
      success: true,
      count: formattedSubCategories.length,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
      data: formattedSubCategories,
    });
  } catch (error) {
    logger.error('Get subcategories error:', error);
    next(error);
  }
};

exports.getSubCategory = async (req, res, next) => {
  try {
    const mongoose = require('mongoose');

    const subCategory = await SubCategory.findById(req.params.id)
      .populate('category', 'name code')
      .populate('createdBy', 'name email')
      .lean();

    if (!subCategory) {
      return res.status(404).json({
        success: false,
        error: 'SubCategory not found',
      });
    }

    // Convert ObjectId buffers to strings
    if (subCategory._id && subCategory._id.buffer && Array.isArray(subCategory._id.buffer)) {
      subCategory._id = new mongoose.Types.ObjectId(Buffer.from(subCategory._id.buffer)).toString();
    } else if (subCategory._id && typeof subCategory._id.toString === 'function') {
      subCategory._id = subCategory._id.toString();
    }

    if (subCategory.category && subCategory.category._id) {
      if (subCategory.category._id.buffer && Array.isArray(subCategory.category._id.buffer)) {
        subCategory.category._id = new mongoose.Types.ObjectId(Buffer.from(subCategory.category._id.buffer)).toString();
      } else if (typeof subCategory.category._id.toString === 'function') {
        subCategory.category._id = subCategory.category._id.toString();
      }
    }

    if (subCategory.createdBy && subCategory.createdBy._id) {
      if (subCategory.createdBy._id.buffer && Array.isArray(subCategory.createdBy._id.buffer)) {
        subCategory.createdBy._id = new mongoose.Types.ObjectId(Buffer.from(subCategory.createdBy._id.buffer)).toString();
      } else if (typeof subCategory.createdBy._id.toString === 'function') {
        subCategory.createdBy._id = subCategory.createdBy._id.toString();
      }
    }

    // Keep _id for update operations, code for display
    const responseData = formatResponse({
      ...subCategory,
      code: subCategory.code,
      category: subCategory.category ? {
        ...subCategory.category,
        code: subCategory.category.code,
      } : subCategory.category,
    });

    res.status(200).json({
      success: true,
      data: responseData,
    });
  } catch (error) {
    logger.error('Get subcategory error:', error);
    next(error);
  }
};

exports.updateSubCategory = async (req, res, next) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        errors: errors.array(),
      });
    }

    let subCategory = await SubCategory.findById(req.params.id);

    if (!subCategory) {
      return res.status(404).json({
        success: false,
        error: 'SubCategory not found',
      });
    }

    const { name, description, category, isActive } = req.body;

    // Store the old category ID before any updates
    const oldCategoryId = subCategory.category;

    if (category) {
      const parentCategory = await Category.findById(category);
      if (!parentCategory) {
        return res.status(404).json({
          success: false,
          error: 'Parent category not found',
        });
      }
    }

    if (name && (name !== subCategory.name || category !== subCategory.category)) {
      const existingSubCategory = await SubCategory.findOne({
        name,
        category: category || subCategory.category,
        _id: { $ne: subCategory._id },
      });
      if (existingSubCategory) {
        return res.status(400).json({
          success: false,
          error: 'SubCategory with this name already exists in this category',
        });
      }
    }

    // Handle category change - update counts
    if (category && category.toString() !== oldCategoryId.toString()) {
      // Decrement count in old category
      await Category.findByIdAndUpdate(oldCategoryId, {
        $inc: { subCategoryCount: -1 },
      });
      // Increment count in new category
      await Category.findByIdAndUpdate(category, {
        $inc: { subCategoryCount: 1 },
      });
    }

    if (name) subCategory.name = name;
    if (description !== undefined) subCategory.description = description;
    if (category) subCategory.category = category;
    if (isActive !== undefined) subCategory.isActive = isActive === true || isActive === 'true';

    if (req.file) {
      if (subCategory.image && subCategory.image.publicId) {
        try {
          await deleteFromCloudinary(subCategory.image.publicId);
        } catch (deleteError) {
          logger.error('Error deleting old image:', deleteError);
        }
      }

      try {
        const uploadResult = await uploadToCloudinary(req.file, 'rush-basket/subcategories');
        subCategory.image = uploadResult;
      } catch (uploadError) {
        logger.error('Cloudinary upload error:', uploadError);
        return res.status(500).json({
          success: false,
          error: 'Failed to upload image',
        });
      }
    }

    await subCategory.save();

    const populatedSubCategory = await SubCategory.findById(subCategory._id)
      .populate('category', 'name code')
      .populate('createdBy', 'name email')
      .lean();

    logger.info(`SubCategory updated: ${subCategory.name} by Admin: ${req.admin.email}`);

    // Keep _id for update operations, code for display
    const responseData = formatResponse({
      ...populatedSubCategory,
      code: populatedSubCategory.code,
      category: populatedSubCategory.category ? {
        ...populatedSubCategory.category,
        code: populatedSubCategory.category.code,
      } : populatedSubCategory.category,
    });

    res.status(200).json({
      success: true,
      message: 'SubCategory updated successfully',
      data: responseData,
    });
  } catch (error) {
    logger.error('Update subcategory error:', error);
    next(error);
  }
};

exports.deleteSubCategory = async (req, res, next) => {
  try {
    const subCategory = await SubCategory.findById(req.params.id);

    if (!subCategory) {
      return res.status(404).json({
        success: false,
        error: 'SubCategory not found',
      });
    }

    if (subCategory.image && subCategory.image.publicId) {
      try {
        await deleteFromCloudinary(subCategory.image.publicId);
      } catch (deleteError) {
        logger.error('Error deleting image from Cloudinary:', deleteError);
      }
    }

    // Store the category ID before deletion
    const categoryId = subCategory.category;

    await SubCategory.findByIdAndDelete(req.params.id);

    // Decrement subCategoryCount in the parent category
    await Category.findByIdAndUpdate(categoryId, {
      $inc: { subCategoryCount: -1 },
    });

    logger.info(`SubCategory deleted: ${subCategory.name} by Admin: ${req.admin.email}`);

    res.status(200).json({
      success: true,
      message: 'SubCategory deleted successfully',
    });
  } catch (error) {
    logger.error('Delete subcategory error:', error);
    next(error);
  }
};

exports.toggleSubCategoryStatus = async (req, res, next) => {
  try {
    const subCategory = await SubCategory.findById(req.params.id);

    if (!subCategory) {
      return res.status(404).json({
        success: false,
        error: 'SubCategory not found',
      });
    }

    subCategory.isActive = !subCategory.isActive;
    await subCategory.save();

    logger.info(`SubCategory status toggled: ${subCategory.name} to ${subCategory.isActive} by Admin: ${req.admin.email}`);

    // Keep _id for update operations, code for display
    const subCategoryData = subCategory.toObject ? subCategory.toObject() : subCategory;
    const responseData = formatResponse({
      ...subCategoryData,
      code: subCategory.code,
    });

    res.status(200).json({
      success: true,
      message: `SubCategory ${subCategory.isActive ? 'activated' : 'deactivated'} successfully`,
      data: responseData,
    });
  } catch (error) {
    logger.error('Toggle subcategory status error:', error);
    next(error);
  }
};

exports.getSubCategoriesByCategory = async (req, res, next) => {
  try {
    const { categoryId } = req.params;
    const isActive = req.query.isActive;

    let query = { category: categoryId };
    if (isActive !== undefined) {
      query.isActive = isActive === 'true';
    }

    const subCategories = await SubCategory.find(query)
      .populate('category', 'name code')
      .sort({ name: 1 })
      .lean();

    // Get total product count for each subcategory and add additional fields
    const subCategoriesWithDetails = await Promise.all(
      subCategories.map(async (subCategory) => {
        try {
          const totalProducts = await Product.countDocuments({
            subCategory: subCategory._id
          });

          // Ensure _id is converted to string for frontend compatibility
          const subCategoryData = {
            ...subCategory,
            _id: subCategory._id ? String(subCategory._id) : subCategory._id,
            code: subCategory.code,
            subCategoryName: subCategory.name || '',
            products: totalProducts || 0,
            totalProducts: totalProducts || 0,
            categoryName: subCategory.category?.name || null,
            category: subCategory.category ? {
              ...subCategory.category,
              _id: subCategory.category._id ? String(subCategory.category._id) : subCategory.category._id,
              code: subCategory.category.code,
            } : subCategory.category,
            status: subCategory.isActive ? 'active' : 'inactive',
          };

          // Keep _id for update operations, code for display
          return formatResponse(subCategoryData);
        } catch (err) {
          logger.error(`Error counting products for subcategory ${subCategory._id}:`, err);
          const subCategoryData = {
            ...subCategory,
            _id: subCategory._id ? String(subCategory._id) : subCategory._id,
            code: subCategory.code,
            subCategoryName: subCategory.name || '',
            products: 0,
            totalProducts: 0,
            categoryName: subCategory.category?.name || null,
            category: subCategory.category ? {
              ...subCategory.category,
              _id: subCategory.category._id ? String(subCategory.category._id) : subCategory.category._id,
              code: subCategory.category.code,
            } : subCategory.category,
            status: subCategory.isActive ? 'active' : 'inactive',
          };
          return formatResponse(subCategoryData);
        }
      })
    );

    res.status(200).json({
      success: true,
      count: subCategoriesWithDetails.length,
      data: subCategoriesWithDetails,
    });
  } catch (error) {
    logger.error('Get subcategories by category error:', error);
    next(error);
  }
};

exports.getSubCategoriesByLocation = async (req, res, next) => {
  try {
    const parsed = parseClientLatLon(req.query);
    if (!parsed) {
      return res.status(400).json({
        success: false,
        error: 'Latitude and longitude are required (latitude & longitude, or lat & lng)',
      });
    }

    const latitude = parsed.latitude;
    const longitude = parsed.longitude;
    const radius = parseFloat(req.query.radius) || 10; // Default 10km radius
    const category = req.query.category; // Optional category filter

    if (parsed.corrected) {
      logger.info('getSubCategoriesByLocation: corrected client lat/lon order (South Asia heuristic)');
    }

    const nearbyVendorIds = [];

    const vendors = await Vendor.find({
      storeAddress: {
        $exists: true,
        $ne: null,
      },
      'storeAddress.latitude': { $exists: true, $ne: null },
      'storeAddress.longitude': { $exists: true, $ne: null },
      isActive: true,
      storeId: { $exists: true },
    }).select('_id storeAddress storeName vendorName serviceRadius');

    if (vendors.length > 0) {
      const vendorsWithDistance = vendors
        .map((v) => {
          const vLat = toNumberCoord(v.storeAddress.latitude);
          const vLon = toNumberCoord(v.storeAddress.longitude);
          const d = calculateDistance(latitude, longitude, vLat, vLon);
          return { ...v.toObject(), distance: d };
        })
        .filter((v) => v.distance != null)
        .sort((a, b) => a.distance - b.distance);

      if (vendorsWithDistance.length > 0 && vendorsWithDistance[0].distance <= radius) {
        nearbyVendorIds.push(vendorsWithDistance[0]._id);
      }
    }

    if (nearbyVendorIds.length === 0) {
      return res.status(200).json({
        success: true,
        message: 'No vendors found within the specified radius',
        count: 0,
        radius: radius,
        userLocation: {
          latitude: latitude,
          longitude: longitude,
        },
        data: [],
      });
    }

    let productQuery = {
      vendor: { $in: nearbyVendorIds },
      approvalStatus: 'approved',
      isActive: true,
    };

    if (category) {
      if (require('mongoose').Types.ObjectId.isValid(category)) {
        productQuery.category = category;
      } else {
        return res.status(400).json({
          success: false,
          error: 'Invalid category ID format',
        });
      }
    }

    const distinctSubIds = await Product.find(productQuery).distinct('subCategory');
    if (distinctSubIds.length === 0) {
      return res.status(200).json({
        success: true,
        message: 'No products found within the specified radius',
        count: 0,
        radius: radius,
        userLocation: {
          latitude: latitude,
          longitude: longitude,
        },
        data: [],
      });
    }

    let subCategoryQuery = {
      _id: { $in: distinctSubIds },
      isActive: true,
    };
    if (category) {
      subCategoryQuery.category = category;
    }
    const subCategories = await SubCategory.find(subCategoryQuery)
      .populate('category', 'name code')
      .sort({ name: 1 })
      .lean();

    const formattedSubCategories = subCategories.map((subCat) => {
      return formatResponse({
        ...subCat,
        code: subCat.code,
        category: subCat.category ? {
          ...subCat.category,
          code: subCat.category.code,
        } : subCat.category,
      });
    });

    res.status(200).json({
      success: true,
      count: formattedSubCategories.length,
      radius: radius,
      userLocation: {
        latitude: latitude,
        longitude: longitude,
      },
      data: formattedSubCategories,
    });
  } catch (error) {
    logger.error('Get subcategories by location error:', error);
    next(error);
  }
};

/**
 * Get subcategories that have nearby products
 * Only returns active subcategories with at least one approved, active, and nearby product
 * Optional category filter
 */
exports.getNearbySubCategories = async (req, res, next) => {
  try {
    const { radius = 10, page = 1, limit = 20, category } = req.query;
    const mongoose = require('mongoose');

    const parsed = parseClientLatLon(req.query);
    const hasLocation = !!parsed;
    const effectiveHasLocation = hasLocation;
    let userLat;
    let userLon;
    let searchRadius;

    if (hasLocation) {
      userLat = parsed.latitude;
      userLon = parsed.longitude;
      searchRadius = parseFloat(radius) || 10;
      if (parsed.corrected) {
        logger.info('getNearbySubCategories: corrected client lat/lon order (South Asia heuristic)');
      }
    }

    const pageNum = parseInt(page) || 1;
    const limitNum = parseInt(limit) || 20;
    const skip = (pageNum - 1) * limitNum;

    const nearbyProductSubCategoryIds = new Set();

    const productQuery = {
      approvalStatus: 'approved',
      isActive: true,
    };

    if (category) {
      if (mongoose.Types.ObjectId.isValid(category)) {
        productQuery.category = category;
      } else {
        return res.status(400).json({
          success: false,
          error: 'Invalid category ID format',
        });
      }
    }

    if (effectiveHasLocation) {
      productQuery.latitude = { $exists: true, $ne: null };
      productQuery.longitude = { $exists: true, $ne: null };
    }

    const products = await Product.find(productQuery)
      .populate('vendor', 'storeAddress serviceRadius')
      .lean();

    if (effectiveHasLocation) {
      const productsWithDistance = products.map(product => {
        if (!product.vendor || !product.vendor.storeAddress) return null;

        const vendorLat = toNumberCoord(product.vendor.storeAddress.latitude);
        const vendorLon = toNumberCoord(product.vendor.storeAddress.longitude);
        if (!Number.isFinite(vendorLat) || !Number.isFinite(vendorLon)) return null;

        const vendorStoreDistance = calculateDistance(userLat, userLon, vendorLat, vendorLon);
        if (vendorStoreDistance == null) return null;

        let productDistance = null;
        const pLat = toNumberCoord(product.latitude);
        const pLon = toNumberCoord(product.longitude);
        if (Number.isFinite(pLat) && Number.isFinite(pLon)) {
          productDistance = calculateDistance(userLat, userLon, pLat, pLon);
        }

        const minDistance = productDistance != null ? Math.min(vendorStoreDistance, productDistance) : vendorStoreDistance;

        if (minDistance <= searchRadius) {
          return { ...product, minDistance };
        }
        return null;
      }).filter(p => p !== null);

      if (productsWithDistance.length > 0) {
        productsWithDistance.sort((a, b) => a.minDistance - b.minDistance);
        const nearestVendorId = productsWithDistance[0].vendor._id.toString();

        productsWithDistance.forEach(product => {
          if (product.vendor._id.toString() === nearestVendorId && product.subCategory) {
            nearbyProductSubCategoryIds.add(String(product.subCategory));
          }
        });
      }
    } else {
      products.forEach((product) => {
        if (product.subCategory) {
          nearbyProductSubCategoryIds.add(String(product.subCategory));
        }
      });
    }

    const subCategoryIdsArray = Array.from(nearbyProductSubCategoryIds).map(id => new mongoose.Types.ObjectId(id));

    // Query subcategories matching those IDs
    const subCategoryQuery = {
      _id: { $in: subCategoryIdsArray },
      isActive: true, // Only return active subcategories
    };

    const subCategories = await SubCategory.find(subCategoryQuery)
      .populate('category', 'name code')
      .populate('createdBy', 'name email')
      .skip(skip)
      .limit(limitNum)
      .sort({ createdAt: -1 })
      .lean();

    // Format results
    const formattedSubCategories = subCategories.map((subCat) => {
      return formatResponse({
        ...subCat,
        code: subCat.code,
        category: subCat.category ? {
          ...subCat.category,
          code: subCat.category.code,
        } : subCat.category,
      });
    });

    const total = await SubCategory.countDocuments(subCategoryQuery);

    if (hasLocation) {
      logger.info(`Nearby subcategories retrieved: Lat: ${userLat}, Lon: ${userLon}, Found: ${total}${category ? `, Category: ${category}` : ''}`);
    } else {
      logger.info(`Subcategories (with products) retrieved: Found: ${total}${category ? `, Category: ${category}` : ''}`);
    }

    res.status(200).json({
      success: true,
      count: formattedSubCategories.length,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total,
        pages: Math.ceil(total / limitNum),
      },
      data: formattedSubCategories,
    });
  } catch (error) {
    logger.error('Get nearby subcategories error:', error);
    if (error.name === 'CastError') {
      return res.status(400).json({
        success: false,
        error: 'Invalid query parameters',
      });
    }
    next(error);
  }
};
